### ISSUE TITLE
babel-polyfill需要在代码里手动导入吗 还是说可以配置

### ISSUE THREAD

**Issue by watsonnnnn** [fenivana/webpack-in-action#17]
RT

**Comment by PanJiaChen** [comment]
https://babeljs.io/docs/en/babel-polyfill/


或者更简单暴力 [polyfill.io](https://cdn.polyfill.io/v2/docs/) 使用它给的一个cdn地址，引入这段 js 之后它会自动判断游览器，加载缺少的那部分polyfill,但国内速度肯能不行，大家可以自己搭 cdn。

[更多相关内容](https://segmentfault.com/a/1190000010106158)

**Comment by watsonnnnn** [comment]
所以这里面用的regenerator-runtime其实是可以理解成一个针对generator的polyfill？[这个链接](https://webpack.js.org/guides/shimming/#further-optimizations)里的代码，是babel-preset-env和babel-polyfill指定配置后的特定polyfill的代码吗？
