### ISSUE TITLE
照着做中间报错

### ISSUE THREAD

**Issue by ioriandy4** [fenivana/webpack-in-action#6]
教程中
[https://github.com/fenivana/webpack-in-action#指定静态资源的url路径前缀](https://github.com/fenivana/webpack-in-action#指定静态资源的url路径前缀)
按照楼主的意思，在webpack.config.js中修改了以下参数
`
output: {
    publicPath: '/assets/'
  },
devServer: {
    // 指定index.html文件的url路径
    historyApiFallback: {
      index: '/assets/'
    }
  }
`

这时执行
`./node_modules/.bin/webpack-dev-server -d --hot`

浏览器打开http://localhost:8100/foo   页面空白

如果执行
`./node_modules/.bin/webpack -p`

在打包出来的文件，也看不到assets目录，而且页面直接预览也是报错
请问要怎么解决？？？

**Comment by jiangfengming** [comment]
`assets`是虚拟目录，实际会重定向到dist目录下的文件。

报错的问题可能是[这个原因](https://github.com/fenivana/webpack-in-action/commit/596cf0f147d393c7768bc50abd83264314e94bd2#diff-1ec7012bff82c6d3b3541b8f8edffb4b)导致的，你编辑一下package.json中的babel选项再试试
