### ISSUE TITLE
请教一下 build之后的dist代码怎么运行

### ISSUE THREAD

**Issue by zhagqn** [fenivana/webpack-in-action#8]
我用http-server 部署了一下 报了个错

![image](https://user-images.githubusercontent.com/5424015/27011817-923ce194-4ef6-11e7-9e4d-546aa8446036.png)

我用的是simple的代码

**Comment by focusqfb** [comment]
@zhagqn 我也是打包之后运行报这个错，你后来怎么解决的，求教
